name: "NPM Publish"

# Publish to NPM only if we're creating a release, and the tag starts with "v" (aka version tag).
on:
  push:
    release:
      types: [created]
      tags: v[0-9]+.[0-9]+.[0-9]+

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository.
      uses: actions/checkout@v2.3.3

    - name: Setup the node environment.
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 14 # use the most recent LTS version
        registry-url: https://registry.npmjs.org/

    - name: Install the package with a clean slate.
      run: npm ci

    - name: Publish the package to NPM.
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
